# Generated by Django 3.2.5 on 2021-08-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbookmodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
