# Generated by Django 3.2.5 on 2021-08-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBook', '0002_alter_addbookmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='createCustomer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
