# Generated by Django 3.2.5 on 2021-08-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBook', '0005_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='BuyBook.createcustomer'),
        ),
    ]
