# Generated by Django 3.2.5 on 2021-08-23 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBook', '0006_purchased_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyBook.createcustomer'),
        ),
    ]
