# Generated by Django 3.2.5 on 2021-08-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBook', '0011_alter_purchased_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased',
            name='user',
        ),
    ]
